; =============================================================================
; ObracunDb - Nastavitve povezave na Firebird bazo
; =============================================================================
;
; PRIMER za lokalni strežnik:
;   DataSource=localhost
;   Database=c:\vasco\2\vasco.fdb
;   Port=3055
;
; PRIMER za oddaljeni IP strežnik:
;   DataSource=192.168.1.100
;   Database=c:\vasco\2\vasco.fdb
;   Port=3050
;
; =============================================================================

[Database]
DataSource=localhost
Database=c:\vasco\2\vasco.fdb
Port=3055
UserID=SYSDBA
Password=masterkey
Charset=UTF8
